{
  lib,
  parameters,
  ...
}: {
  # import our dconf settings that have been autogenerated
  # TODO(emily): Figure out why weather? doesn't work?
  imports = [
    ./extensions

    ./keybinds.nix
    ./background.nix
  ];

  config = lib.mkMerge [
    {
      gtk.enable = true;

      dconf.settings = {
        "org/gnome/desktop/interface/color-scheme" = {
          prefer-dark = true;
        };
        "org/gnome/desktop/peripherals/mouse" = {
          accel-profile = "flat";
        };
      };

      qt = {
        enable = true;
        style.name = "kvantum";
        platformTheme.name = "kvantum";
      };
    }
    # TODO(emily): This is a byproduct of NVIDIA Prime, really need
    # to figure that out
    (lib.mkIf (parameters.machine.type == "dell-precision-5690") {
      services.xserver.enable = true;
    })
  ];
}
