{
  parameters,
  pkgs,
  lib,
  config,
  ...
}: {
  # import our dconf settings that have been autogenerated
  # TODO(emily): Figure out why weather? doesn't work?
  imports = [./dconf.nix];

  options = {
    dconf-location = lib.mkOption {
      type = lib.types.str;
      # TODO(emily); figure out how to reference host directory without impure
      default = "${config.home.homeDirectory}/config/home/de/gnome";
    };
  };

  config = {
    # utilize dconf2nix to allow us to cache any dconf changes we make
    # this gives is the ability to make updates through the gnome UI, then record them automatically
    # into nix config
    home.shellAliases = let
      command = "dconf dump / | nix run nixpkgs#dconf2nix >";

      to_cwd = "${command} dconf.nix";
      to_install = "${command} ${config.dconf-location}/dconf.nix";
    in {
      generate-dconf = to_cwd;
      install-dconf = to_install;
    };

    dconf.settings = {
      "org/gnome/desktop/background" = let wp-uri = "file://${../../../config/wallpaper.jpg}"; in {
        color-shading-type = "solid";
        picture-uri = wp-uri;
        picture-uri-dark = wp-uri;
      };
      "org/gnome/screensaver" = let wp-uri = "file://${../../../config/lockscreen.jpg}"; in {
        picture-uri = wp-uri;
      };
    };
  };
}
