[burn-my-windows-profile]
fire-enable-effect=true
apparition-enable-effect=true
aura-glow-enable-effect=true
broken-glass-enable-effect=true
doom-enable-effect=true
energize-a-enable-effect=true
energize-b-enable-effect=true
focus-enable-effect=true
glide-enable-effect=true
glitch-enable-effect=true
hexagon-enable-effect=true
incinerate-enable-effect=true
incinerate-animation-time=500
matrix-enable-effect=true
mushroom-enable-effect=true
paint-brush-enable-effect=true
pixelate-enable-effect=true
pixel-wheel-enable-effect=true
pixel-wipe-enable-effect=true
portal-enable-effect=true
rgbwarp-enable-effect=true
snap-enable-effect=true
team-rocket-enable-effect=true
trex-enable-effect=true
tv-enable-effect=true
tv-glitch-enable-effect=true
wisps-enable-effect=true
aura-glow-animation-time=500
broken-glass-animation-time=500
doom-animation-time=500
energize-a-animation-time=500
energize-b-animation-time=500
fire-animation-time=500
focus-animation-time=500
glitch-animation-time=500
glide-animation-time=500
hexagon-animation-time=500
matrix-animation-time=500
mushroom-animation-time=500
paint-brush-animation-time=500
pixelate-animation-time=500
pixel-wheel-animation-time=500
pixel-wipe-animation-time=500
portal-animation-time=500
rgbwarp-animation-time=500
snap-animation-time=500
team-rocket-animation-time=500
trex-animation-time=500
tv-animation-time=500
tv-glitch-animation-time=500
wisps-animation-time=500
apparition-animation-time=500